[package]
name = "damnpacket"
version = "0.1.0"
authors = ["Jude Taylor <me@jude.bio>"]

[dependencies]
ansi_term = "0.9"
htmlescape = "*"
log = "*"
string = { path = "../string" }

[dependencies.nom]
version = "*"
features = [ "verbose-errors" ]
